project_id = "adhoebapzgtjrexhwame"

[functions.bursary-assistant]
verify_jwt = false

[functions.allocate-bursary]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.process-allocations]
verify_jwt = false

[functions.send-sms-notifications]
verify_jwt = false

[functions.check-deadlines]
verify_jwt = false

[functions.setup-users]
verify_jwt = false