// Excel export — two sheets: Households (Dimension 1) + Beneficiaries (Dimension 2).
// Preserves hierarchy: beneficiary rows carry their tracking_number so hierarchy
// can be reconstructed downstream (pivots, Power BI, etc.).
import * as XLSX from "xlsx";
import type { Household } from "@/lib/household/types";
import type { GeneratedReportMeta, ReportMetrics } from "./types";
import { toBeneficiaryRows } from "./metricsEngine";

export function exportHouseholdReportExcel(
  households: Household[],
  metrics: ReportMetrics,
  meta: GeneratedReportMeta,
  filename = `bursary-report-${Date.now()}.xlsx`,
): void {
  const wb = XLSX.utils.book_new();

  // Sheet 1 — Summary
  const summary = [
    ["Bursary-KE Allocation Report"],
    ["Generated", meta.generatedAt],
    ["Generated By", meta.generatedBy],
    ["Version", meta.version],
    [],
    ["Households", metrics.households],
    ["Beneficiaries", metrics.beneficiaries],
    ["Secondary Beneficiaries", metrics.secondaryBeneficiaries],
    ["Higher Education Beneficiaries", metrics.higherEdBeneficiaries],
    ["Avg Beneficiaries / Household", metrics.avgBeneficiariesPerHousehold],
    ["Disabled Beneficiaries", metrics.disabledBeneficiaries],
    ["Budget Requested (KES)", metrics.budgetRequested],
    ["Budget Recommended (KES)", metrics.budgetRecommended],
    ["Budget Allocated (KES)", metrics.budgetAllocated],
    ["Budget Remaining (KES)", metrics.budgetRemaining],
    ["Approved Households", metrics.approvedHouseholds],
    ["Pending Households", metrics.pendingHouseholds],
    ["Rejected Households", metrics.rejectedHouseholds],
  ];
  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.aoa_to_sheet(summary),
    "Summary",
  );

  // Sheet 2 — Households (Dimension 1)
  const hhRows = households.map((h) => ({
    Tracking: h.tracking_number,
    Parent: h.parent_name_masked,
    County: h.parent_county,
    Ward: h.parent_ward ?? "",
    Status: h.status,
    Students: h.total_students,
    HouseholdIncome: h.household_income ?? "",
    PovertyTier: h.poverty_tier ?? "",
    PovertyScore: h.poverty_score ?? "",
    ReleasedToTreasury: h.released_to_treasury ? "Yes" : "No",
    CreatedAt: h.created_at,
  }));
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(hhRows), "Households");

  // Sheet 3 — Beneficiaries (Dimension 2)
  const rows = toBeneficiaryRows(households).map((r) => ({
    Tracking: r.tracking_number,
    Parent: r.parent_name_masked,
    County: r.parent_county,
    Ward: r.parent_ward ?? "",
    Beneficiary: r.student_name_masked,
    Level: r.education_level,
    Institution: r.institution ?? "",
    ClassForm: r.class_form ?? "",
    YearOfStudy: r.year_of_study ?? "",
    Status: r.status,
    Recommended: r.recommended_amount ?? 0,
    Allocated: r.allocated_amount ?? 0,
    Disability: r.has_disability ? "Yes" : "No",
    NCPWD: r.ncpwd_number ?? "",
  }));
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), "Beneficiaries");

  // Sheet 4 — Filters used (audit trail)
  const filterRows = Object.entries(meta.filters).map(([k, v]) => ({
    Filter: k,
    Value: v == null ? "" : String(v),
  }));
  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.json_to_sheet(
      filterRows.length ? filterRows : [{ Filter: "(none)", Value: "" }],
    ),
    "Filters",
  );

  XLSX.writeFile(wb, filename);
}
