// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/track-application.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var track_application_default = defineTool({
  name: "track_application",
  title: "Track bursary application",
  description: "Look up the current status of a Bursary KE application by its tracking number (BKE-XXXXXX). To protect applicant privacy, the applicant's phone number OR national ID must also be provided as a verification value \u2014 without a matching value nothing is returned. Never returns names or other PII.",
  inputSchema: {
    tracking_number: z.string().describe("Public tracking number issued at submission, e.g. BKE-ABC123."),
    verification_type: z.enum(["phone", "national_id"]).describe("Which private detail is being used to verify ownership of the application."),
    verification_value: z.string().min(4).describe("The parent's phone number (any Kenyan format) or national ID, matching verification_type.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tracking_number, verification_type, verification_value }) => {
    const url = `${process.env.SUPABASE_URL}/functions/v1/track-application`;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${key}`,
        apikey: key
      },
      body: JSON.stringify({
        trackingNumber: tracking_number.trim().toUpperCase(),
        verificationType: verification_type,
        verificationValue: verification_value.trim()
      })
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok) {
      const msg = body?.message ?? body?.error ?? `HTTP ${res.status}`;
      return { content: [{ type: "text", text: String(msg) }], isError: res.status >= 500 };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(body, null, 2) }],
      structuredContent: body
    };
  }
});

// src/lib/mcp/tools/list-active-bursaries.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
var list_active_bursaries_default = defineTool2({
  name: "list_active_bursaries",
  title: "List active bursary adverts",
  description: "List currently open Bursary KE adverts. Optionally filter by county or ward. Returns title, county, ward, deadline, and required documents so applicants know what to prepare.",
  inputSchema: {
    county: z2.string().trim().optional().describe("Kenyan county name to filter by, e.g. 'Nairobi'."),
    ward: z2.string().trim().optional().describe("Ward name to filter by (case-insensitive)."),
    limit: z2.number().int().positive().max(50).optional().describe("Max number of adverts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ county, ward, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("bursary_adverts").select(
      "id,title,county,ward,deadline,description,required_documents,min_award_per_student,max_award_per_student,is_active"
    ).eq("is_active", true).gte("deadline", (/* @__PURE__ */ new Date()).toISOString()).order("deadline", { ascending: true }).limit(limit ?? 20);
    if (county) q = q.ilike("county", county);
    if (ward) q = q.ilike("ward", ward);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length ? JSON.stringify(rows, null, 2) : "No active bursary adverts match those filters right now."
        }
      ],
      structuredContent: { count: rows.length, adverts: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bursary-ke-mcp",
  title: "Bursary KE",
  version: "0.1.0",
  instructions: "Public read-only tools for Bursary KE (Kenya). Use `list_active_bursaries` to discover open bursary adverts by county or ward, and `track_application` to check the status of a submitted application by its BKE-XXXXXX tracking number. No personally identifiable information (names, phone numbers, ID numbers) is ever returned.",
  tools: [track_application_default, list_active_bursaries_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
