
INSERT INTO public.bursary_adverts (county, ward, title, description, deadline, budget_amount, venues, required_documents, is_active)
VALUES 
  ('Nairobi', 'Westlands', 'Nairobi County Bursary Fund 2026', 'Supporting students from Nairobi County pursuing secondary and tertiary education. Priority given to orphans and students with disabilities.', '2026-05-15T23:59:59+03:00', 25000000, '[{"name": "Nairobi County Hall", "phone": "+254 20 222 1234", "address": "City Hall Way, Nairobi"}, {"name": "Westlands Sub-County Office", "phone": "+254 20 444 5678", "address": "Waiyaki Way, Westlands"}]'::jsonb, ARRAY['National ID (Parent/Guardian)', 'Birth Certificate', 'School Admission Letter', 'Fee Structure', 'Academic Transcripts', 'Death Certificate (if orphan)', 'Medical Certificate (if disabled)'], true),
  
  ('Kisumu', 'Kisumu Central', 'Kisumu County Education Bursary 2026', 'Lake region educational bursary program targeting vulnerable students from Kisumu County.', '2026-05-20T23:59:59+03:00', 15000000, '[{"name": "Kisumu County Government HQ", "phone": "+254 57 202 3456", "address": "Oginga Odinga Street, Kisumu"}, {"name": "Kisumu Central Ward Office", "phone": "+254 57 203 7890", "address": "Jomo Kenyatta Highway, Kisumu"}]'::jsonb, ARRAY['National ID (Parent/Guardian)', 'Birth Certificate', 'School Admission Letter', 'Fee Structure', 'KCPE/KCSE Results', 'Chief''s Letter', 'Death Certificate (if orphan)'], true),

  ('Nakuru', 'Nakuru Town East', 'Nakuru County Bursary Scheme 2026', 'Rift Valley educational support for secondary and university students from low-income households.', '2026-06-01T23:59:59+03:00', 18000000, '[{"name": "Nakuru County Assembly", "phone": "+254 51 221 4567", "address": "Kenyatta Avenue, Nakuru"}, {"name": "Nakuru Town East Office", "phone": "+254 51 221 8901", "address": "George Morara Road, Nakuru"}]'::jsonb, ARRAY['National ID (Parent/Guardian)', 'Birth Certificate', 'School Admission Letter', 'Fee Structure', 'Academic Transcripts', 'Death Certificate (if orphan)', 'Pay Slip or Income Declaration'], true),

  ('Kiambu', 'Thika Town', 'Kiambu County Student Bursary 2026', 'Central region bursary fund for bright students from disadvantaged backgrounds in Kiambu County.', '2026-05-30T23:59:59+03:00', 20000000, '[{"name": "Kiambu County Headquarters", "phone": "+254 66 222 3456", "address": "Kiambu Road, Kiambu Town"}, {"name": "Thika Sub-County Office", "phone": "+254 67 223 7890", "address": "Kenyatta Highway, Thika"}]'::jsonb, ARRAY['National ID (Parent/Guardian)', 'Birth Certificate', 'School Admission Letter', 'Fee Structure', 'Academic Transcripts', 'Church/Mosque Letter', 'Death Certificate (if orphan)'], true),

  ('Machakos', 'Machakos Town', 'Machakos County Bursary Awards 2026', 'Eastern region educational support program for students from Machakos County.', '2026-05-25T23:59:59+03:00', 10000000, '[{"name": "Machakos County Government Office", "phone": "+254 44 221 5678", "address": "Machakos Town Center"}]'::jsonb, ARRAY['National ID (Parent/Guardian)', 'Birth Certificate', 'School Admission Letter', 'Fee Structure', 'KCPE/KCSE Results', 'Chief''s Letter'], true),

  ('Uasin Gishu', 'Kapseret', 'Uasin Gishu County Bursary Program 2026', 'North Rift educational funding for talented students from low-income families in Uasin Gishu County.', '2026-06-15T23:59:59+03:00', 14000000, '[{"name": "Uasin Gishu County HQ", "phone": "+254 53 206 3456", "address": "Uganda Road, Eldoret"}]'::jsonb, ARRAY['National ID (Parent/Guardian)', 'Birth Certificate', 'School Admission Letter', 'Fee Structure', 'Academic Transcripts', 'Death Certificate (if orphan)'], true),

  ('Kilifi', 'Kilifi Town', 'Kilifi County Education Support 2026', 'Coastal educational bursary supporting students from Kilifi County to access quality education.', '2026-06-10T23:59:59+03:00', 8000000, '[{"name": "Kilifi County Government Office", "phone": "+254 42 752 1234", "address": "Hospital Road, Kilifi"}]'::jsonb, ARRAY['National ID (Parent/Guardian)', 'Birth Certificate', 'School Admission Letter', 'Fee Structure', 'Chief''s Letter', 'Medical Certificate (if disabled)'], true),

  ('Nyeri', 'Nyeri Town', 'Nyeri County Bursary Fund 2026', 'Mt. Kenya region educational support for students pursuing secondary and higher education.', '2026-05-28T23:59:59+03:00', 12000000, '[{"name": "Nyeri County Headquarters", "phone": "+254 61 203 4567", "address": "Kimathi Way, Nyeri"}]'::jsonb, ARRAY['National ID (Parent/Guardian)', 'Birth Certificate', 'School Admission Letter', 'Fee Structure', 'Academic Transcripts', 'Death Certificate (if orphan)'], true);
